### ISSUE TITLE
Error stepping through macro generated code

### ISSUE THREAD

**Issue by Keno** [JuliaDebug/Debugger.jl#77] opened 2019-03-15 22:48 UTC
I was trying to debug the following
```
using Core.Compiler: IRCode, argextype, Const
function generate_rule(rule, stmt, done_sym)
    if isexpr(rule, :call)
        call_match = quote
            isexpr($stmt, :call) || @goto $(done_sym)
            ft = argextype($stmt.args[1], ir, ir.sptypes)
            isa(ft, Const) || @goto $(done_sym)
            ft.val === $(rule.args[1]) || @goto $(done_sym)
        end
        argsyms = [gensym() for _ = 1:length(rule.args)-1]
        quote
            $call_match
            $(map(i->:($(argsyms[i]) = $stmt.args[1+$i]), 1:length(argsyms))...)
            $(map(i->generate_rule(rule.args[1+i], argsyms[i], done_sym), 1:length(argsyms))...)
        end
    elseif isexpr(rule, :(::))
        argsym = gensym()
        return quote
            sT = argextype($stmt.args[2], ir, ir.sptypes)
            sT ⊑ $(rule.args[2]) || @goto $(done_sym)
            $(argsym) = $stmt.args[1]
            $(generate_rule(rule.args[1], argsym, done_sym))
        end
    elseif isa(rule, Symbol)
        name = String(rule)
        name == "_" && return nothing
        :($rule = $stmt)
    end
end

function generate_replacement(replacement)
    :(ir.stmts[idx] = Expr(:call, size, bc))
end

macro rule(expr)
    @capture(expr, pattern_ => replacement_)
    label = gensym()
    esc(quote
        $(generate_rule(pattern, :stmt, label))
        $(generate_replacement(replacement))
        return
        @label($label)
    end)
end

function array_optimize!(ir, idx)
    stmt = ir.stmts[idx]
    @rule size(materialize(bc::Broadcasted)) => size(bc)
end
```
Error is:
```
ERROR: BoundsError: attempt to access 4-element Array{UInt64,1} at index [5]
Stacktrace:
 [1] getindex at ./array.jl:728 [inlined]
 [2] #print_sourcecode#28(::Debugger.LineNumbers.SourceFile, ::typeof(Debugger.print_sourcecode), ::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::String, ::Int64, ::Int64) at /home/keno/.julia/packages/Debugger/rxJeq/src/printing.jl:149
 [3] print_sourcecode at /home/keno/.julia/packages/Debugger/rxJeq/src/printing.jl:149 [inlined]
 [4] print_status(::Base.TTY, ::Frame) at /home/keno/.julia/packages/Debugger/rxJeq/src/printing.jl:88
 [5] (::getfield(Debugger, Symbol("##5#9")){REPL.Terminals.TTYTerminal,Debugger.DebuggerState,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at /home/keno/.julia/packages/Debugger/rxJeq/src/repl.jl:54
 [6] #invokelatest#1 at ./essentials.jl:790 [inlined]
 [7] invokelatest at ./essentials.jl:789 [inlined]
 [8] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /home/keno/julia/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2306
 [9] run_interface at /home/keno/julia/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2300 [inlined]
 [10] #RunDebugger#3(::Bool, ::typeof(Debugger.RunDebugger), ::Frame, ::REPL.LineEditREPL, ::REPL.Terminals.TTYTerminal) at /home/keno/.julia/packages/Debugger/rxJeq/src/repl.jl:82
 [11] RunDebugger(::Frame, ::REPL.LineEditREPL, ::REPL.Terminals.TTYTerminal) at /home/keno/.julia/packages/Debugger/rxJeq/src/repl.jl:4 (repeats 2 times)
 [12] top-level scope at /home/keno/.julia/packages/Debugger/rxJeq/src/Debugger.jl:82
```
Reproduce with e.g.:
```
ir = Core.Compiler.inflate_ir((@code_typed gcd(10, 20)).first)
@enter array_optimize!(ir, 5)
```

**Comment by fredrikekre** [comment] 2019-03-16 07:02
Duplicate of #71 maybe?

**Closed** 2019-03-16 10:12 UTC
