### ISSUE TITLE
Debugger Crash

### ISSUE THREAD

**Issue by tueboesen** [JuliaDebug/Debugger.jl#213] opened 2019-08-31 08:42 UTC
I get the following crash:

```
debug> ERROR: ccall return type Ptr should have an element type (not Ptr{<:T})
Stacktrace:
 [1] ccall_cholmod_l_allocate_sparse_libcholmod_da167d10_cbca_11e9_24a9_0d2419d3e675(::Int64, ::Int64, ::Int64, ::Bool, ::Bool, ::Int64, ::Int32, ::Array{UInt8,1}, ::Val{Float64}) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\optimize.jl:329
 [2] #invokelatest#1(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Any, ::Any, ::Vararg{Any,N} where N) at .\essentials.jl:742
 [3] invokelatest(::Any, ::Any, ::Vararg{Any,N} where N) at .\essentials.jl:741
 [4] bypass_builtins(::JuliaInterpreter.Frame, ::Expr, ::Int64) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:183
 [5] #evaluate_call_recurse!#37(::Bool, ::Function, ::Any, ::JuliaInterpreter.Frame, ::Expr) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:207
 [6] evaluate_call_recurse! at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:206 [inlined]
 [7] eval_rhs(::Any, ::JuliaInterpreter.Frame, ::Expr) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:381
 [8] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Any, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:521
 [9] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:560
 [10] finish!(::Any, ::JuliaInterpreter.Frame, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\commands.jl:14
 [11] finish_and_return! at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\commands.jl:29 [inlined]
 [12] #evaluate_call_recurse!#37(::Bool, ::Function, ::Any, ::JuliaInterpreter.Frame, ::Expr) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:243
 [13] evaluate_call_recurse! at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:206 [inlined]
 [14] eval_rhs(::Any, ::JuliaInterpreter.Frame, ::Expr) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:381
 [15] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Any, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:438
 [16] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:560
 [17] finish!(::Any, ::JuliaInterpreter.Frame, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\commands.jl:14
 [18] finish_and_return! at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\commands.jl:29 [inlined]
 [19] #evaluate_call_recurse!#37(::Bool, ::Function, ::Any, ::JuliaInterpreter.Frame, ::Expr) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:243
 [20] evaluate_call_recurse! at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:206 [inlined]
 [21] eval_rhs(::Any, ::JuliaInterpreter.Frame, ::Expr) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:381
 [22] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Any, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:521
 ... (the last 7 lines are repeated 3 more times)
 [44] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:560
 [45] finish!(::Any, ::JuliaInterpreter.Frame, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\commands.jl:14
 [46] finish_and_return! at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\commands.jl:29 [inlined]
 [47] #evaluate_call_recurse!#37(::Bool, ::Function, ::Any, ::JuliaInterpreter.Frame, ::Expr) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:243
 [48] evaluate_call_recurse! at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:206 [inlined]
 [49] eval_rhs(::Any, ::JuliaInterpreter.Frame, ::Expr) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:381
 [50] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Any, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:438
 [51] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:560
 [52] finish!(::Any, ::JuliaInterpreter.Frame, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\commands.jl:14
 [53] finish_and_return! at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\commands.jl:29 [inlined]
 [54] #evaluate_call_recurse!#37(::Bool, ::Function, ::Any, ::JuliaInterpreter.Frame, ::Expr) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:243
 [55] evaluate_call_recurse! at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:206 [inlined]
 [56] eval_rhs(::Any, ::JuliaInterpreter.Frame, ::Expr) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:381
 [57] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Any, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:521
 [58] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:560
 [59] finish!(::Any, ::JuliaInterpreter.Frame, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\commands.jl:14
 [60] finish_and_return! at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\commands.jl:29 [inlined]
 [61] #evaluate_call_recurse!#37(::Bool, ::Function, ::Any, ::JuliaInterpreter.Frame, ::Expr) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:243
 [62] evaluate_call_recurse! at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:206 [inlined]
 [63] eval_rhs(::Any, ::JuliaInterpreter.Frame, ::Expr) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:381
 [64] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Any, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:438
 [65] step_expr!(::Any, ::JuliaInterpreter.Frame, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\interpret.jl:560
 [66] finish!(::Any, ::JuliaInterpreter.Frame, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\commands.jl:14
erpreter\VHjfX\src\commands.jl:29 [68] finish_stack!(::Any, ::JuliaInterpreter.Frame, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\commands.jl:59 [69] #debug_command#57(::Nothing, ::Function, ::Any, ::JuliaInterpreter.Frame, ::Symbol, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\commands.jl:444 [70] debug_command(::Any, ::JuliaInterpreter.Frame, ::Symbol, ::Bool) at C:\Users\alyfl\.julia\packages\JuliaInterpreter\VHjfX\src\commands.jl:386 [71] (::getfield(Atom.JunoDebugger, Symbol("##51#53")){Bool})() at C:\Users\alyfl\.julia\packages\Atom\Wouyw\src\debugger\stepper.jl:152 [72] evalscope(::getfield(Atom.JunoDebugger, Symbol("##51#53")){Bool}) at C:\Users\alyfl\.julia\packages\Atom\Wouyw\src\debugger\stepper.jl:387 [73] startdebugging(::JuliaInterpreter.Frame, ::Bool) at C:\Users\alyfl\.julia\packages\Atom\Wouyw\src\debugger\stepper.jl:103
```

The code I use is the following, which runs fine when run without debugger, but will crash when it gets to the line: dU = A\df

```
using SparseArrays
using EllipsisNotation
using Statistics
using LinearAlgebra

sumdrop(A, d) = dropdims(sum(A,dims=setdiff([1:ndims(A);],[d])),dims=(setdiff([1:ndims(A);],[d])...,)) #sums all dimensions but the designated dimension and collapse all other dimensions

function SoftmaxLoss(U,C)
    nex = size(C,2)

    S = exp.(U)
    F = -sum(sum(C.*(U))) + sum(log.(sum(S,dims=1)))
    F = F ./ nex
    dF = (-C + S ./ sum(S,dims=1)) / nex
    return F,dF

end

function AdjacencyMatrix_(x;nn=9)
  nd = ndims(x)           #Number of dimensions
  n = size(x,nd)          #number of data points
  knn = min(n,nn)
  I=zeros(Int64,knn,n)
  J=zeros(Int64,knn,n)
  di = zeros(typeof(x[1]),n,knn)  #TODO Fix all cases like this to instead use eltype.
  for i=1:n
      r = x .- x[..,i]
      d=sumdrop(r.*r , nd)
      idx = sortperm(d[:])
      di[i,:] = d[idx[1:knn]]
      I[:,i] = i.*ones(knn,1)
      J[:,i] = idx[1:knn]
  end
  A = SparseArrays.sparse(I[:],J[:],ones(typeof(x[1]),length(J[:]),1)[:],n,n)
  A = A+A'  # Warning this is not a normal adjencymatrix, since we have values that are 2 instead of 1 in it as well!
  return A, Statistics.median(di)
end

function GraphLaplacian_(X,A,ϵ)
    n=size(A,1)
    I,J,_=findnz(A)
    nd = ndims(X)
    aa=sumdrop((X[..,I] .- X[..,J]).^2 , nd)
    V = exp.(-aa./ϵ)
    W = SparseArrays.sparse(I,J,V[:],n,n);
    Ws=sum(W,dims=2)
    D = LinearAlgebra.Diagonal(Ws[:])
    Dh = LinearAlgebra.Diagonal(1 ./ sqrt.(Ws[:]))
    L = D-W;
    L = Dh*L*Dh;
    L = oftype(L[1],0.5)*(L+L') #Get rid of small asymmetries
    return L
end

function SemiSupLearn(X,idx,C,L,α,β,maxIter)
    nl = length(idx)  #number of labeled points
    nx = size(X,2)  #number of examples
    nc = size(C,1)  #number of classes
    nk = size(C,2)  #number of known labels

    A = L + β*sparse(I, size(L,1),size(L,2))
    P = sparse(collect(1:nl),idx,ones(nl),nl,nx) # Generate a projection matrix

    U = zeros(nc,nx) #Initialize the solution
    iter = 1;
    muls = 1;
    Cpred = similar(U)
    while true
        F,dF = SoftmaxLoss(Matrix(U*P'),C)
        dF = dF*P

        #Compute the objective
        f  = 0.5*α*tr(U*L*U') + F
        if f<0
           error("negative loss")
        end
        df = α*L*U' + dF'
        # Compute a step
        dU = A\df
        lsIter = 1;
        Utry = 0
        while true
            Utry = U - muls*dU';
            Ftry,_ = SoftmaxLoss(Utry*P',C);
            ftry = 0.5*α*tr(Utry*L*Utry') + Ftry;
            if ftry < f
                break;
            end
            muls = muls/2;
            lsIter = lsIter+1;
            if lsIter>20
                error("LSB")
            end
        end
        if lsIter == 1
            muls = muls*1.3;
        end
        U = Utry;
        Cpred = exp.(U)./sum(exp.(U),dims=1)
        iter = iter+1
        if iter>maxIter
            break
        end
    end
    return U,Cpred

end

X = [0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1;0.1 0.2 0.3 0.4 1.5 1.6 1.7 1.8 1.9 2]
idx = [1,8]
C = [1 0 ; 0 1]
A,ϵ   = AdjacencyMatrix_(X,nn=2)
L = GraphLaplacian_(X,A,ϵ)
α = 1
β = 1e-3
maxIter = 10
nl = length(idx)
Is=collect(1:nl)
Js=idx
Vs=ones(nl)
nx=size(X,2)
P = sparse(Is,Js,Vs,nl,nx)
SemiSupLearn(X,idx,C,L,α,β,maxIter)
```

**Comment by KristofferC** [comment] 2019-09-02 06:40
Duplicate of https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/285 which we haven't fixed yet.

**Closed by KristofferC** 2019-09-02 06:40 UTC
